name: CI-HF-JOBSLOGGER

on:
  pull_request:
        branches: 
          - master
          - develop    
  push:
    branches: 
      - master
      - develop  
jobs:
  build:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
          
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
